<?php
$aCartas = array(
    array("imagen" => "png/2_of_clubs.png", "puntuacion" => 2),
    array("imagen" => "png/2_of_diamonds.png", "puntuacion" => 2),
    array("imagen" => "png/2_of_hearts.png", "puntuacion" => 2),
    array("imagen" => "png/2_of_spades.png", "puntuacion" => 2),
    array("imagen" => "png/3_of_clubs.png", "puntuacion" => 3),
    array("imagen" => "png/3_of_diamonds.png", "puntuacion" => 3),
    array("imagen" => "png/3_of_hearts.png", "puntuacion" => 3),
    array("imagen" => "png/3_of_spades.png", "puntuacion" => 3),
    array("imagen" => "png/4_of_clubs.png", "puntuacion" => 4),
    array("imagen" => "png/4_of_diamonds.png", "puntuacion" => 4),
    array("imagen" => "png/4_of_hearts.png", "puntuacion" => 4),
    array("imagen" => "png/4_of_spades.png", "puntuacion" => 4),
    array("imagen" => "png/5_of_clubs.png", "puntuacion" => 5),
    array("imagen" => "png/5_of_diamonds.png", "puntuacion" => 5),
    array("imagen" => "png/5_of_hearts.png", "puntuacion" => 5),
    array("imagen" => "png/5_of_spades.png", "puntuacion" => 5),
    array("imagen" => "png/6_of_clubs.png", "puntuacion" => 6),
    array("imagen" => "png/6_of_diamonds.png", "puntuacion" => 6),
    array("imagen" => "png/6_of_hearts.png", "puntuacion" => 6),
    array("imagen" => "png/6_of_spades.png", "puntuacion" => 6),
    array("imagen" => "png/7_of_clubs.png", "puntuacion" => 7),
    array("imagen" => "png/7_of_diamonds.png", "puntuacion" => 7),
    array("imagen" => "png/7_of_hearts.png", "puntuacion" => 7),
    array("imagen" => "png/7_of_spades.png", "puntuacion" => 7),
    array("imagen" => "png/8_of_clubs.png", "puntuacion" => 8),
    array("imagen" => "png/8_of_diamonds.png", "puntuacion" => 8),
    array("imagen" => "png/8_of_hearts.png", "puntuacion" => 8),
    array("imagen" => "png/8_of_spades.png", "puntuacion" => 8),
    array("imagen" => "png/9_of_clubs.png", "puntuacion" => 9),
    array("imagen" => "png/9_of_diamonds.png", "puntuacion" => 9),
    array("imagen" => "png/9_of_hearts.png", "puntuacion" => 9),
    array("imagen" => "png/9_of_spades.png", "puntuacion" => 9),
    array("imagen" => "png/10_of_clubs.png", "puntuacion" => 10),
    array("imagen" => "png/10_of_diamonds.png", "puntuacion" => 10),
    array("imagen" => "png/10_of_hearts.png", "puntuacion" => 10),
    array("imagen" => "png/10_of_spades.png", "puntuacion" => 10),
    array("imagen" => "png/ace_of_clubs.png", "puntuacion" => [1, 11]),
    array("imagen" => "png/ace_of_diamonds.png", "puntuacion" => [1, 11]),
    array("imagen" => "png/ace_of_hearts.png", "puntuacion" => [1, 11]),
    array("imagen" => "png/ace_of_spades.png", "puntuacion" => [1, 11]),
    array("imagen" => "png/jack_of_clubs2.png", "puntuacion" => 10),
    array("imagen" => "png/jack_of_diamonds2.png", "puntuacion" => 10),
    array("imagen" => "png/jack_of_hearts2.png", "puntuacion" => 10),
    array("imagen" => "png/jack_of_spades2.png", "puntuacion" => 10),
    array("imagen" => "png/king_of_clubs2.png", "puntuacion" => 10),
    array("imagen" => "png/king_of_diamonds2.png", "puntuacion" => 10),
    array("imagen" => "png/king_of_hearts2.png", "puntuacion" => 10),
    array("imagen" => "png/king_of_spades2.png", "puntuacion" => 10),
    array("imagen" => "png/queen_of_clubs2.png", "puntuacion" => 10),
    array("imagen" => "png/queen_of_diamonds2.png", "puntuacion" => 10),
    array("imagen" => "png/queen_of_hearts2.png", "puntuacion" => 10),
    array("imagen" => "png/queen_of_spades2.png", "puntuacion" => 10)
);